### PR TITLE
Reference other schemas using the $ref property

### PR DESCRIPTION
**Pull request by Dexterp37**
This additionally cleans up the validate_pings.py file.
More importantly, this allows to reference other schemas
living in other files: this way we don't have to define
common sections (e.g. environment) in all the ping definitons
using them.

### CODE REVIEW

**Comment by Dexterp37** [comment]
@mreid-moz this might be especially interesting for you, so flagging you here :-D

I'm wondering if this way of referencing the schemas will work on when the schemas are used on the pipeline side. Any clue there?

**Comment by Dexterp37** [comment]
Hah, I just saw #46 :-D That's interesting timing!

**Comment by mreid-moz** [comment]
@Dexterp37 can you take a look at #55 and see if it will suit your needs?

**Comment by Dexterp37** [comment]
It does!

**Pull request closed without merging**
