### PR TITLE
Bug 1637340 - openTabCount in core ping

### PR DESCRIPTION
**Pull request by fbertsch**
Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [ ] Update `include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by mreid-moz** [comment]
👍

**Comment by mreid-moz** [comment]
@fbertsch - Safe to assume that the `"ecosystem_device_id"` change is unrelated?

**Comment by jklukas** [comment]
> Safe to assume that the "ecosystem_device_id" change is unrelated?

Most definitely. That integration report is very old. I will kick off tests again to verify.

**Comment by jklukas** [comment]
Actually, I think we'd need to rebase this on master to get a clean integration report.

**Pull request merged**
