### PR TITLE
Bug 1709383 - Add contentWin32kLockdownState to schema

### PR DESCRIPTION
**Pull request by marti4d**
Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] If adding a new field, the field should have a description (see #576 for an example)
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by marti4d** [comment]
I wasn't able to perform the last action -- Ran the script, got `Permission to mozilla-services/mozilla-pipeline-schemas.git denied to marti4d`

**Comment by acmiyaguchi** [comment]
Hmm, the error is strange when I manually push this for integration test. I checked it out manually and it looks fine:

```diff
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.bhr.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.bhr.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.crash.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.crash.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.dnssec-study-v1.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.dnssec-study-v1.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.event.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.event.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.first-shutdown.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.first-shutdown.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.heartbeat.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.heartbeat.4.txt
113a114
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.main.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.main.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.modules.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.modules.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.new-profile.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.new-profile.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.saved-session.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.saved-session.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.shield-icq-v1.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.shield-icq-v1.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.testpilot.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.testpilot.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.third-party-modules.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.third-party-modules.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.uninstall.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.uninstall.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.untrusted-modules.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.untrusted-modules.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.update.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.update.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
diff --new-file --exclude '*.bq' /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/cdea1a5a/telemetry.voice.4.txt /Users/amiyaguchi/Work/mozilla-pipeline-schemas/integration/36f8b3dc/telemetry.voice.4.txt
112a113
> root.environment.settings.sandbox.content_win32k_lockdown_state INT64
```

Could I ask you to add an example of this new field to a validation document in `validation/telemetry`?

**Review by fbertsch — CHANGES_REQUESTED** [review]
Backing up @acmiyaguchi here: Please add a test of this new field.

**Comment by marti4d** [comment]
@fbertsch @acmiyaguchi I have added an example to one of the validation scripts. (I think...)

I didn't see any instructions for adding validation in the readme, so I have no idea what I'm doing and I only picked this file because some previous commit also modified it.

This field is allowed to take on values {1, 2, 3, 4}, so hopefully this allows that somehow...¯\_(ツ)_/¯

**Review by fbertsch — APPROVED** [review]
LGTM. Your validation schema is good!

**Pull request merged**
