### PR TITLE
Bug 1513590: Add Pocket Fire-TV Events Ping

### PR DESCRIPTION
**Pull request by fbertsch**
Checklist for reviewer:

- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by fbertsch** [comment]
This should match the schema here: https://docs.google.com/document/d/1E7yTd-KzYNJbSvIGm1ZkvZvrvTGKy7Prz2OtLjRQqvY/edit?ts=5be9d858

**Comment by fbertsch** [comment]
@whd can we get this deployed?

**Comment by whd** [comment]
I'll do this today, and update here when it's done.

**Comment by whd** [comment]
This has been deployed.

**Pull request merged**
