### PR TITLE
Bug 1776797 - Replace scenario with improve_suggest_experience_checke…

### PR DESCRIPTION
**Pull request by ncloudioj**
…d in quicksuggest pings

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

This fixes [Bug 1776797](https://bugzilla.mozilla.org/show_bug.cgi?id=1776797).

r? @quiiver @jklukas

### CODE REVIEW

**Review by quiiver — APPROVED** [review]
i'm not totally sure what the deprecation process is. my assumption is that the absence of fields in the schema is still considered valid but unexpected fields would cause schema invalidation. assuming that is true: lgtm 👍

**Review by jklukas — APPROVED** [review]

**Comment by ncloudioj** [comment]
> i'm not totally sure what the deprecation process is. my assumption is that the absence of fields in the schema is still considered valid but unexpected fields would cause schema invalidation.

I think we will keep them both. The old Firefox versions will continue sending `scenario` without the new field. The newer version (103+) will do the opposite. None of them are required, so we should be fine.

**Comment by jklukas** [comment]
> my assumption is that the absence of fields in the schema is still considered valid but unexpected fields would cause schema invalidation

Unless a field is marked in the `required` list of its enclosing `object` in the JSON schema, it is considered optional and a document will not fail validation due to the missing field.

Unexpected fields are generally allowed and will show up in `additional_properties` in the BigQuery tables. In most cases, this means that there's no required order for getting a new field added to the schema here and getting it added in the client.

**Comment by jklukas** [comment]
The `post-artifacts` CI task is failing because it can't provide credentials to PRs from forks.

@quiiver - To get this passing, see the push-to-trigger-ci instructions in https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional

**Comment by quiiver** [comment]
triggered build here https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas?branch=trigger-integration

**Pull request merged**
