### PR TITLE
Add 'openglCompositing' and 'wrCompositor' to schema

### PR DESCRIPTION
**Pull request by jrmuizel**
These correspond to telemetry added in
https://bugzilla.mozilla.org/show_bug.cgi?id=1649215
and https://bugzilla.mozilla.org/show_bug.cgi?id=1648304

Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [x] Update `include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by jklukas** [comment]
This looks good to me. I'm tagging @acmiyaguchi for additional review since this touches all pings with environment. Do you concur that the test results here indicate no regressions in validation for existing pings?

**Comment by acmiyaguchi** [comment]
Yes, although the corresponding field should be added to one of the validation pings to ensure it's being captured in a unit test.

**Comment by jrmuizel** [comment]
> Can you add a validation document with some expected values, using https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/validation/telemetry/main.4.min.pass.json as a base?

Done.

**Comment by jrmuizel** [comment]
Thanks. When can I expect the schema change to be applied?

**Pull request merged**
