### PR TITLE
Bug 1728420 - Add a schema for the Messaging System Spotlight template

### PR DESCRIPTION
**Pull request by piatra**
Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] If adding a new field, the field should have a description (see #576 for an example)
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [x] Update `templates/include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by piatra** [comment]
Not sure if that integration step is needed, is that different from the circleci tests that already triggered?
Tried following the instructions in the readme but I think I'm missing some permissions
```
Permission to mozilla-services/mozilla-pipeline-schemas.git denied
```

**Comment by jklukas** [comment]
> Not sure if that integration step is needed, is that different from the circleci tests that already triggered?

For this case of adding a new schema, the integration tests aren't really needed. They're mostly for verifying that a change to a schema doesn't cause a sample of existing documents to fail validation.

> Tried following the instructions in the readme but I think I'm missing some permissions

The checklist is for the reviewer rather than the author, so you're good. Triggering integration tests requires commit access to the repository.

**Comment by relud** [comment]
re-assigning review to person who reviewed the last 3 changes to messaging-system schemas: @jklukas

**Comment by jklukas** [comment]
CI is currently failing due to https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/696 ; this will likely be blocked until we figure out the CI problem. Otherwise, this PR looks good to merge.

**Review by jklukas — APPROVED** [review]

**Pull request merged**
