### PR TITLE
Consider speed as optional in parquet output

### LINKED ISSUE #313: output.telemetry_telemetry_pre_account_4_parquet_s3 process_message returned: -1 column 'speedMHz' is required
/CC @badboy 

The pre-account ping schemas were deployed recently and I'm seeing occasional errors of the type above.  It looks like this is because the json schema has the field as required but nullable, but the parquet schema has it as required. I'm a little hazy as to null vs optional, @trink would know more, but making the field optional in parquet is probably sufficient to fix the issue. You should be able to reproduce this in the tests by making the [field](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/validation/telemetry/pre-account.4.sample.pass.json#L56) null.

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/pre-account/pre-account.4.schema.json#L89-L93
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/pre-account/pre-account.4.parquetmr.txt#L35-L37

### PR DESCRIPTION
**Pull request by badboy**
Fixes #313

Checklist for reviewer:

- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [ ] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by mreid-moz** [comment]
Please also add the rendered stuff in `schemas/` (sorry!)

**Comment by badboy** [comment]
D'oh! No idea how I managed to _not_ commit those.

**Comment by badboy** [comment]
Can this land? @fbertsch or @mreid-moz?

**Comment by whd** [comment]
I'll roll this out on Monday.

**Comment by whd** [comment]
I've rolled this out and it appears to work from re:dash (athena). If the resulting schema update via p2h update breaks access from some frontend I will try to sort it out with :robotblake. (Aside: the majority of errors for this dataset are because of the unrelated known issue at https://bugzilla.mozilla.org/show_bug.cgi?id=1547563).

**Pull request merged**
