### PR TITLE
Add all allowed process types to main ping

### PR DESCRIPTION
**Pull request by sunahsuh**
Doesn't look like I can actually add this to Mark's PR since it's from a personal fork. Fingers crossed we avoid merge conflicts!

Checklist for reviewer:

- [ ] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [ ] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by jklukas** [comment]
Is it possible/easy to see what changes will be made to the BQ schema as a result of this. It looks like there are ~400 fields associated with the `parent` process; if the number is similar for other processes, we're adding more than 1000 fields here. So I have some concern about how much room we have before hitting the 10,000 column limit for main ping.

**Comment by sunahsuh** [comment]
@fbertsch would know in more detail but – all histograms.json and scalars.yaml have a "recorded in processes" property that specify which ones they might possible appear under. From a cursory search, we're looking at three additional metrics (plus the events tuples for the three new processes)

**Comment by sunahsuh** [comment]
Huh, what's the bulk of the new probes? I only saw a few recorded in `socket`, basically

**Comment by fbertsch** [comment]
The killers are `all`, `all_children`, and `all_childs`. Who knows if they ever _actually_ record in those but we have to assume that is the case.

**Pull request merged**
