### PR TITLE
Bug 1661581 - Add blank schemas for Pioneer-core add-on

### PR DESCRIPTION
**Pull request by akkomar**
This adds blank schemas for [pioneer-core pings](https://bugzilla.mozilla.org/show_bug.cgi?id=1661581#c2), to be updated when schemas are finalized.

@jcchuang if it's not too late, I'd suggest to rename document names and drop `pioneer-core-` prefix:
* `pioneer-core-survey` -> `survey`
* `pioneer-core-telemetry` -> `telemetry`

`pioneer-core` is the name of the namespace and we don't need to repeat it in the doc type names.

@mreid-moz @acmiyaguchi this PR would need to be changed accordingly if doctypes as updated^.

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [ ] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

### CODE REVIEW

**Review by jklukas — APPROVED** [review]
This looks technically correct to me, and I'm glad to see the `"bq_metadata_format": "pioneer"` piece (which is a very new requirement) implemented.

I agree that if possible we should drop `pioneer-core-` from the ping names. In addition, I would suggest avoiding the name `telemetry` as a document type if possible, as it could easily be confused with the `telemetry` namespace, and it generally a somewhat overloaded term.

**Comment by jcchuang** [comment]
@akkomar @jklukas I'll update the doc type names. I'll rename `pioneer-core-survey` to `survey`. I'm looking into alternative names for `pioneer-core-telemetry`. A potential candidate is `probes`. I'll keep you posted when I have a final choice.

**Comment by jcchuang** [comment]
Just fyi, please use the following names for the data schemas: `survey` and `probes`

**Comment by acmiyaguchi** [comment]
Changed the names for the survey and probes pings, and also added in the pioneer-enrollment ping.

**Review by acmiyaguchi — APPROVED** [review]

**Comment by acmiyaguchi** [comment]
These schemas should be enough to start development feedback with the notebook environment. Data will show up under `additional_properties` as JSON.

**Pull request merged**
