### PR TITLE
Bug 1736117 - Add request_id to QuickSuggest tables

### PR DESCRIPTION
**Pull request by ncloudioj**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

Note that although Merino currently uses the UUID/v4 for `request_id`, I didn't specify it in the `pattern` field as it's subject to future changes.

r? @jklukas

### CODE REVIEW

**Comment by jklukas** [comment]
I was just thinking earlier today that this change to Merino flow may be a good opportunity to recreate the schema. In particular, I would propose creating a new schema `suggest-impression v2` which would allow us to do the following:

- Add the `request_id`
- Drop the outdated "quicksuggest" branding from the ping name
- Remove the `search_query` and `matched_keywords` fields, removing uncertainty about whether the ping contains user query data

This would also make it easier for us to monitor the rate of submissions to the online branch vs. the merino branch.

**Comment by ncloudioj** [comment]
Good point. We can certainly do that.

Let's see what else do we need for this migration given that the existing offline&online rollouts will be sticking around for some time.
* Pings from those offline & online rollouts will continue to be sent to the old tables
* Merino-backed impressions will go to the new impression table, shall we do this for clicks as well now, or later?
* Update the derived table (`event_aggregates`)
* We might not be able to know the search queries for impressions unless Merino is allowed to log them and send them to the pipeline, just wanted to point that out

cc: @rebecca-burwei

**Comment by jklukas** [comment]
> for Merino-backed impressions, we will set the search_query and matched_keywords to an empty string (unfortunately, we can leave them out as they both are required fields)

Making these fields optional would be a compatible change to the schema. We can remove them from the `required` list in this PR, and once it flows through the schema deployment process the pipeline will stop rejecting messages that are missing those fields.

**Comment by ncloudioj** [comment]
Oh, I didn't know that was an allowed change to make. I will update my patch for that.

**Pull request merged**
