### PR TITLE
Fix #363 - Update `payload.info` in main ping schema

### LINKED ISSUE #363: Add `payload.info` to the main ping schema
The main ping schema is currently missing most of the fields inside of `payload.info`. The Firefox source docs has [some information on this](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/main-ping.html#info).

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This fixes #363 using the environment information on [this page](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/main-ping.html). I've also checked the additionalProperties to double check the types of each of the fields. The table in [this issue](https://github.com/mozilla/gcp-ingestion/issues/711#issue-472594034) shows the types and frequency of each field.

I left out `addons` and `flashVersion` because the docs say the fields are obsolete. Based on the data, it seems that they're being reported by a significant number of clients. It might be useful to add here just to increase the coverage of the schema and to reduce the size of additional properties.

Checklist for reviewer:

- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by mreid-moz** [comment]
The reports from the integration test are empty again - can you do a manual run of the error report?

Otherwise, this looks good!

**Comment by acmiyaguchi** [comment]
@mreid-moz integration tests require #361 to work

**Comment by mreid-moz** [comment]
Do we need special handling here to address splitting these fields out of `additional_properties` in BQ?

**Comment by acmiyaguchi** [comment]
@mreid-moz: Yes, queries at that cross today's date boundary are going to need to read from both fields. It makes @relud's [main summary reimplementation](https://github.com/mozilla/bigquery-etl/pull/258) a bit tricky. It might be possible to backfill the fields using DML, but it's not a small change.

**Comment by relud** [comment]
as per [whd's comment on snake casing addtional_properties](https://github.com/mozilla/gcp-ingestion/pull/713#issuecomment-515595703), the table should get backfilled from protobuf after it moves to prod.

We should merge this before then, so the [main summary reimplementation](https://github.com/mozilla/bigquery-etl/pull/258) can simply read from the new column.

if it does impact that query, then i'll just modify it to use `COALESCE` between `additionalProperties` and the new column.

**Pull request merged**
