### PR TITLE
Bug 1567339 - Add parameters to attribution in environment data

### PR DESCRIPTION
**Pull request by acmiyaguchi**
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1567339)

Checklist for reviewer:

- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by mreid-moz** [comment]
The changes look good to me, but I triggered the integration test and it generated empty reports - can you see what's happening there?

**Comment by acmiyaguchi** [comment]
They're hidden, but there. There's no diff, but there are the two reports available:

https://circleci.com/gh/mozilla-services/mozilla-pipeline-schemas/1457#artifacts/containers/0

**Comment by acmiyaguchi** [comment]
@mixedpuppy Thanks for the review! I wasn't involved with the construction of the payload, so it's nice to get review from someone who was. I'm not sure the `funnel_` prefix would have been caught without your input. 

You'll notice someone else from data engineering is involved with review, but I think the data consumer should update (or at least review) the schema, since it has an significant impact on downstream analysis. For context, this repository is used to perform validation during data ingestion and to update the table schemas in sql.telemetry.mozilla.org.

**Comment by acmiyaguchi** [comment]
@mreid-moz I double checked the integration reports, and you're right that they are just empty objects. I'll take a look at the docker image to see what's going on.

**Comment by acmiyaguchi** [comment]
[Here's a manual run of the integration tests](https://gist.github.com/acmiyaguchi/9a7b1e9265af2b6ee64b32aa0310a04a) which comes up with an empty diff. I'ved filed a PR in mozilla-services/edge-validator#44 to fix this.

**Pull request merged**
