### PR TITLE
Bug 1688698 - Add 'source' to TopSites schemas in Contextual Services

### PR DESCRIPTION
**Pull request by ncloudioj**
Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] If adding a new field, the field should have a description (see #576 for an example)
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

This is a follow up for #656 

r? @sunahsuh @BenWu

### CODE REVIEW

**Review by BenWu — APPROVED** [review]
Looks good to me.  Can you also add this to the proposal?

**Review by sunahsuh — APPROVED** [review]
Looks fine to me – only comment is, will we expand the options for this field in the future? If so, how will we remember to keep the list updated here? Just wondering if being more permissive default would make sense, or if filtering out pings with sources outside this list is very important.

**Comment by ncloudioj** [comment]
> Will we expand the options for this field in the future?  If so, how will we remember to keep the list updated here? Just wondering if being more permissive default would make sense, or if filtering out pings with sources outside this list is very important.

Good point, though I don't think we will expand this list for the foreseeable future. In case that we do so at some point and we forget to update it here, we should be able to capture it by the validation error monitors (we'd like to have this as one of the system health monitors).

**Comment by sunahsuh** [comment]
Okay – I think @fbertsch can help point you to doctype-specific validation error monitors

**Pull request merged**
