### PR TITLE
Add Shield study schemas to `pioneer-study` namespace

### PR DESCRIPTION
**Pull request by motin**
As per https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/199#issuecomment-433963945

### CODE REVIEW

**Comment by motin** [comment]
Using schemas from https://github.com/gregglind/shield-study-schemas/tree/master/schemas-client, with parquet schemas from https://github.com/gregglind/shield-study-schemas/tree/master/schemas-parquet adapted to only correspond to the payload group

**Comment by trink** [comment]
Probably overkill but I added  a sanity check, for shield-study, that validates the schema in the actual pipeline using the deployed packages if you are interested https://github.com/mozilla-services/lua_sandbox_extensions/pull/401
r+ it if you want it included

**Comment by motin** [comment]
@trink Additional sanity checks are always fine with me :) - adding corresponding checks for shield-study-addon and shield-study-error may also be of interest. 

Any feedback regarding this PR? Can it be merged? Once it is merged, how long time does it take before the shield-study, shield-study-addon and shield-study-error pings will be deliverable via the Pioneer pipeline?

**Comment by trink** [comment]
Here are my long and short term recommendations but I am not the owner of this repository ;)

## Long Term
I am not sure what is up with the gregglind repository.  This repository is the source of truth since it is what is deployed to production.  Ideally any auto schema generation would be moved to this repository and the build would take care of it all.

## Short Term
1) Since these schemas are being manually maintained here at the moment I would +1 @mreid-moz recommendation to break out the common payload section of each and include them in the telemetry/pioneer-study full schemas (this allows future updates to be made in a single place).

```
template/include/telemetry/shieldStudyPayload.1.schema.json
template/include/telemetry/shieldStudyAddonPayload.1.schema.json
template/include/telemetry/shieldStudyErrorPayload.1.schema.json
```
and then in templates/telemetry/shield-study/shield-study.3.schema.json
```json
 "payload": {
  @TELEMETRY_SHIELDSTUDYPAYLOAD_1_JSON@
 },
```
and then in templates/pioneer-study/shield-study.3.schema.json
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  @TELEMETRY_SHIELDSTUDYPAYLOAD_1_JSON@
}
```
... repeat for the other files and parquet schemas

2) The worst case is, the duplication is accepted for now and we take on a little more technical debt.  If we plan on implementing the long term solution I am fine with punting on the template refactor above.

## Deployment
Ops is aware of this change and the production deployment can happen quickly (i.e. usually the same day as the merge assuming the test/stage deployments don't raise any issues)

**Comment by motin** [comment]
Thanks @trink that is a great answer! If we can get a short term solution that includes duplication rolling as soon as possible (so that testing of the pipeline via shield utils can commence), I'll make sure to open a new PR that addresses the deduplication aspect specifically - either using templating against the repo or by extended @gregglind's repository as soon as we have decided which way to go.

**Comment by trink** [comment]
In that case you need to run the build process (to generate the schema artifacts) https://github.com/mozilla-services/mozilla-pipeline-schemas#adding-a-new-schema and then add the artifacts to this PR.

**Comment by motin** [comment]
> In that case you need to run the build process (to generate the schema artifacts) https://github.com/mozilla-services/mozilla-pipeline-schemas#adding-a-new-schema and then add the artifacts to this PR.

Ah, sorry, missed that. Now the templates, generated artifacts, validation files are all in the PR and the tests pass locally.

CI seems to be broken though, failing on:
> Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')

**Comment by motin** [comment]
Deduplication no longer. Tests still passing locally.

Integration CI fails on:
> Unable to locate credentials. 

Ready to merge?

**Pull request merged**
