### PR TITLE
Bug 1633525 - Remove frecency-update pings

### PR DESCRIPTION
**Pull request by fbertsch**
Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [x] Update `include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by fbertsch** [comment]
Looks like the new integration tests are failing. cc @acmiyaguchi

**Comment by acmiyaguchi** [comment]
This looks like its caused  by the push to integration script. The build step contains the tests for detecting diffs in the BigQuery schemas, but the CircleCI configuration filters out this step. This should resolve itself in master and doesn't block this PR.

**Comment by mreid-moz** [comment]
In [Bug 1633928](https://bugzilla.mozilla.org/show_bug.cgi?id=1633928), there's some discussion of flagging data we wish to delete using `UnwantedDataException`s - is that going to be done here before merging this PR?

**Comment by whd** [comment]
> In [Bug 1633928](https://bugzilla.mozilla.org/show_bug.cgi?id=1633928), there's some discussion of flagging data we wish to delete using `UnwantedDataException`s - is that going to be done here before merging this PR?

Yes, we discussed this in the May 4th technical check-in and agreed that since we will likely always want to create `UnwantedDataException`s anyway (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1635592 came eventually after the deletion in https://bugzilla.mozilla.org/show_bug.cgi?id=1626490), we can significantly simplify deploy semantics by always requiring that datasets pending deletion have all their data marked  as `UnwantedDataException` in gcp-ingestion before the MPS PR is merged.

I'd therefore expect that before this PR is merged we'd deploy a change like https://github.com/mozilla/gcp-ingestion/pull/1278.

**Review by mreid-moz — CHANGES_REQUESTED** [review]
Please don't merge this until we've solidified the process around deleting data in [Bug 1633928](https://bugzilla.mozilla.org/show_bug.cgi?id=1633928).

**Comment by relud** [comment]
closing this won't-fix with intent to revisit after @mreid-moz's bug is worked out.

**Pull request closed without merging**
