### PR TITLE
Add schema for Rally version of news and disinfo study

### PR DESCRIPTION
**Pull request by akohlbre**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)
- [ ] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [ ] If the PR comes from a fork, trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by akohlbre** [comment]
Hm, I see the tests failed because it couldn't find `cmake3` when building the docker image. I had the same problem when I was testing, but assumed it was some local misconfiguration -- was able to build the image and then test by switching `cmake3` to just `cmake` in `Dockerfile`. I'm not sure what the root cause of this is, though, since I was seeing it before I made any changes at all.

**Comment by jklukas** [comment]
> Hm, I see the tests failed because it couldn't find `cmake3` when building the docker image. I had the same problem when I was testing, but assumed it was some local misconfiguration -- was able to build the image and then test by switching `cmake3` to just `cmake` in `Dockerfile`. I'm not sure what the root cause of this is, though, since I was seeing it before I made any changes at all.

I was able to reproduce this and filed https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/681 to track.

**Comment by jklukas** [comment]
We implemented the cmake3 -> cmake change as you suggested, so tests should be able to run here now if you rebase on `main`.

**Review by acmiyaguchi — APPROVED** [review]
This looks fine to me, with the rebase changes for passing the tests. Is there a link for tracking the rest of this work that can be referenced here?

**Comment by akohlbre** [comment]
Thanks both! The best link overall is just the repo for this study: https://github.com/citp/news-disinformation-study (the Rally version of the study is on branch `ws-migration` right now, but that's moving to `main` shortly).

**Comment by acmiyaguchi** [comment]
> Thanks both! The best link overall is just the repo for this study: https://github.com/citp/news-disinformation-study (the Rally version of the study is on branch `ws-migration` right now, but that's moving to `main` shortly).

Do you mind embedding this into the schema description/comment at the top-level?

**Comment by acmiyaguchi** [comment]
Great, thanks!

**Pull request merged**
