### PR TITLE
Bug 1460433: Add schema for new launcher-process-failure ping

### PR DESCRIPTION
**Pull request by dblohm7**
Checklist for reviewer:

- [ ] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [ ] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

For glean changes:
- [ ] Update `include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by dblohm7** [comment]
@akkomar The ping structure has now been finalized and landed on the client side. I have updated the schema with the changes and properly included the generated files.

**Comment by akkomar** [comment]
@dblohm7 Thanks! Can you rebase this onto the latest `dev` branch? (sorry but I can't do it myself since your changes are on forked `dev` instead of feature branch)

**Comment by dblohm7** [comment]
@akkomar done. Sorry about that; my github-fu is a little bit rusty!

**Comment by akkomar** [comment]
Hey @whd, can we deploy this?

**Comment by whd** [comment]
@akkomar we can, but I want to double check that this ping has its own namespace and is not a telemetry ping, because it looks like it could be a telemetry ping (in which case, it should go under the telemetry namespace).

**Comment by akkomar** [comment]
@whd yes, it has its own namespace: https://hg.mozilla.org/integration/autoland/rev/7733f36c6e38#l2.55

**Comment by whd** [comment]
Cool, this will go out later today, after which I will update this issue.

**Comment by whd** [comment]
This schema has been deployed.

**Pull request merged**
