### PR TITLE
Update the environment bundle to include the services object. Fixes #442

### LINKED ISSUE #442: Add "services" object to telemetry environment bundle
In https://bugzilla.mozilla.org/show_bug.cgi?id=1238810 we added some new fields to the telemetry environment. In particular, there's a new "services" top level object, which is optional and can contain two boolean properties, "accountEnabled", and "syncEnabled".

### PR DESCRIPTION
**Pull request by thomcc**
Checklist for reviewer:

- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
Could you create or add a validation document that includes this section too? Otherwise this looks good to me.

**Comment by thomcc** [comment]
@acmiyaguchi Like that? Not 100% sure how to test this locally, I'm gathering it requires that I set up docker?

**Comment by acmiyaguchi** [comment]
Looks good. And testing at the moment does require docker because we pull in hindsight to run validation.

**Comment by acmiyaguchi** [comment]
It looks like CircleCI is having some issues at the moment ([status.circleci.com](https://status.circleci.com/)), so we'll have to wait until it kicks back in.

**Pull request merged**
