### PR TITLE
Add schema for core ping version 10

### PR DESCRIPTION
**Pull request by jklukas**
Version was increased as part of
https://hg.mozilla.org/mozilla-central/rev/5cb4e28e1eb8

Checklist for reviewer:

- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

### CODE REVIEW

**Comment by whd** [comment]
Note that the way we're provisioning core ping parquet output on the AWS infra is such that the schema for v9 is applied to all core pings, not just v9, which is why there is no difference between the v9 and v10 parquet schemas. As such, there may be no need to add a v10 parquet output.

What this brings to light is that we're probably not doing validation of core v10 pings json-side, since this schema is missing (but the relevant change was applied to v9). The behavior of the current infra, absent a schema, is to assume the payload is valid.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1410156

**Comment by jklukas** [comment]
Given that context, I agree it doesn't make sense to add the parquet schemas for v10. Will remove.

**Comment by whd** [comment]
It looks like it would also be technically correct to revert the change on the v9 json schema that is for v10 pings (but not revert it for the v9 parquet output, which is really for all core pings). Given the confusion here, it may make sense to rename the v9 parquet output to remove its version, but that will require a redeploy of the ingestion infrastructure.

**Comment by whd** [comment]
That it did not require a version bump is probably why @fbertsch added the changes to v9. My guess is that he was unaware that the client team was going to bump the version due to this addition.

At any rate, leaving v9 as-is seems reasonable to me.

**Comment by fbertsch** [comment]
Also, @whd is correct - we somehow missed on our end that this was going to be a version bump on the client.

**Pull request merged**
