### PR TITLE
Add `previous_os_version` to `default-browser-agent/default-browser`.

### PR DESCRIPTION
**Pull request by ncalexan**
This completes https://bugzilla.mozilla.org/show_bug.cgi?id=1850149 for Legacy telemetry.  (Glad I realized this was necessary before it made it to release channel!)

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)
- [ ] If coming from a fork, run integration tests: `./.github/push-to-trigger-integration <username>:<branchname>`

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by scholtzan — COMMENTED** [review]
ci is failing because the change needs to be propagated to schemas/firefox-installer/install/install.1.schema.json by running mkdir release && cd release && cmake ..

or by manually applying this change:

```diff
6 changes: 5 additions & 1 deletion 6
[schemas/default-browser-agent/default-browser/default-browser.1.schema.json](https://github.com/mozilla-services/mozilla-pipeline-schemas/compare/802?expand=1#diff-a87c8ce4ca3c96c8d85853ec77b4492e9022e0566bd0e4924c60816c91d47cf1)
@@ -47,7 +47,7 @@
      "type": "string"
    },
    "os_version": {
      "description": "Windows version numnber in major.minor.build.UBR format (UBR is optional, only available on Win10)",
      "description": "Windows version number in major.minor.build.UBR format (UBR is optional, only available on Win10)",
      "type": "string"
    },
    "previous_default_browser": {
@@ -57,6 +57,10 @@
    "previous_notification_action": {
      "description": "What action was taken by the user the last time a toast notification was displayed",
      "type": "string"
    },
    "previous_os_version": {
      "description": "The Windows OS version before it was changed to the current setting. The possible values are the same as for ``os_version``. The OS does not keep track of the previous OS version, so the agent records this information itself. That means that it will be inaccurate until the first time the default is changed after the agent task begins running. Before then, the value of ``previous_os_version`` will be the same as ``os_version``. This value is updated every time the Default Agent runs, so when the default browser is first changed the values for ``os_version`` and ``previous_os_version`` will be different. But on subsequent executions of the Default Agent, the two values will be the same.",
      "type": "string"
    }
  },
  "required": [
```

**Comment by ncalexan** [comment]
I'm frustrated that this means that I have to run a bunch of stuff locally because I made the initial patch in the Github Web UI to avoid cloning :(  I'll get to this when I can.

**Comment by scholtzan** [comment]
I created a new PR with the generated schemas (https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/803)

**Comment by fbertsch** [comment]
@ncalexan just to be clear here - we don't recommend using the legacy telemetry tools here in this repo (for this reason and others). When you use Glean there is no need to do anything manual in the pipeline, and we have a similar generation mechanism for the main ping probes. We understand that it is frustrating, which is why we created tools to remove this step!

**Comment by ncalexan** [comment]
> @ncalexan just to be clear here - we don't recommend using the legacy telemetry tools here in this repo (for this reason and others). When you use Glean there is no need to do anything manual in the pipeline, and we have a similar generation mechanism for the main ping probes. We understand that it is frustrating, which is why we created tools to remove this step!

Totally understood, and we're using Glean in parallel to this legacy telemetry until we can switch over entirely.

My frustration is with the repo layout which has checked in genereated artifacts, increasing the cost of making a change yet further.  But I can understand that there won't be movement here, what with the trend towards Glean and better tooling across the board.

**Pull request closed without merging**
