### PR TITLE
simple schemas

### PR DESCRIPTION
**Pull request by SamPenrose**
Add payload budget schemas per bug 1370529.

### CODE REVIEW

**Comment by trink** [comment]
The telemetry directory is for Firefox client data schemas; this in not a supported ping type.  Also in the future you will want to run cmake to create the artifacts which are also committed.

**Comment by SamPenrose** [comment]
I'll run cmake. Which directory would you like it in?

**Comment by trink** [comment]
What is the data source?

**Comment by SamPenrose** [comment]
https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/moz_telemetry/sandboxes/heka/analysis/moz_telemetry_payload_size.lua#L42

**Comment by mreid-moz** [comment]
Can we call these "payload-size" rather than "budget"?

**Comment by trink** [comment]
It should go here https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/master/templates/heka/telemetry (no JSON/input schema as it is a Heka message)

**Comment by SamPenrose** [comment]
RFAL.

**Comment by fbertsch** [comment]
Closed in favor of #103

**Pull request closed without merging**
