### PR TITLE
Bug 1907663 - Add scale factor fields to gfx

### PR DESCRIPTION
**Pull request by saschanaz**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)
- [ ] If coming from a fork, run integration tests: `./.github/push-to-trigger-integration <username>:<branchname>`

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by BenWu — COMMENTED** [review]
You can do this is by updating the environment schema template [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/templates/include/telemetry/environment.1.schema.json) and then running the [build instructions in the readme](https://github.com/mozilla-services/mozilla-pipeline-schemas?tab=readme-ov-file#cmake-build-instructions), which. should give the same output.  CI is failing because the template doesn't match the output

**Comment by saschanaz** [comment]
Thanks, I should have suspected that there should be a better option than regex 😅 for now I tried manual fix.

**Review by BenWu — APPROVED** [review]

**Comment by BenWu** [comment]
The column should show up tomorrow.  We seem to be getting significant volume already (in the additional_properties column)

**Comment by saschanaz** [comment]
Thank you!

**Pull request merged**
