### PR TITLE
Bug 1623439 Replace shield_id with experiments for activity-stream etc

### PR DESCRIPTION
**Pull request by ncloudioj**
…system

Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional) and review the report posted in the comments.

For glean changes:
- [ ] Update `include/glean/CHANGELOG.md`

r? @jklukas

### CODE REVIEW

**Comment by ncloudioj** [comment]
This fixes [bug 1623439](https://bugzilla.mozilla.org/show_bug.cgi?id=1623439), which has been causing lots of pain while conducting experiments for Activity Stream and Messaging System.

We used to do string matching (`activity-stream`) to filter out the non-ActivityStream experiments in the telemetry, this has become super error-prone for experiment designers. Now that BigQuery allows us to easily store the whole experiment information, we'd like to lift this limitation.

Specifically, we are looking to deprecate the `shield_id` filed, and to add a new filed `experiments` of the type "REPEATED RECORD". It follows the same structure as the `experiments` defined in [telemetry.environments](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/templates/include/telemetry/environment.1.schema.json#L316) without including the `type` and `enrollmentID` fields.

**Comment by jklukas** [comment]
Note that it may be a few days before changes are deployed due to pipeline instability issues we're currently working through.

**Comment by ncloudioj** [comment]
@jklukas Thanks!

> Note that it may be a few days before changes are deployed due to pipeline instability issues we're currently working through.

Copy that, will put the client-side patch on hold.

**Comment by jklukas** [comment]
> Copy that, will put the client-side patch on hold.

If you release the client-side patch early, the new info will go to additional_properties. But it won't cause any operational trouble for the pipeline.

**Comment by ncloudioj** [comment]
On a side note, if there is no experiment, shall we send an empty object, like `"experiments": {}`, or just omit this field in the payload?

**Comment by jklukas** [comment]
> On a side note, if there is no experiment, shall we send an empty object, like `"experiments": {}`, or just omit this field in the payload?

Either is fine. Omitting the field from the payload will lead to the field being NULL in BQ. Note, though, that the document would fail to validate if you set `"experiments": null`; you would need to specify `"type": ["null", "object"]` to support that.

**Comment by ncloudioj** [comment]
OK, will always send an object then.

Thanks for confirming this!

**Pull request merged**
