### PR TITLE
Add messaging-system experiment ping

### PR DESCRIPTION
**Pull request by crankycoder**
This adds a schema for the messaging-system personalization experiment pings.

cc/ @motin 

Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant
- [x] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [x] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

For glean changes:
- [x] Update `include/glean/CHANGELOG.md`

### CODE REVIEW

**Comment by crankycoder** [comment]
@jklukas thanks - I've moved the template, schema and validation files into `messaging-system/personalization-experiment` and renamed files where necessary.

r?

**Comment by crankycoder** [comment]
ach.  I made the changes and force pushed up into my branch, so I can't seem to reply to the change requested message.  The file move and rename is in 72fc113

**Comment by jklukas** [comment]
I'm skipping integration tests here, as this is a new docType with no existing data.

**Comment by jklukas** [comment]
Within 24 hours, there should be an automated schema deploy which will cause new tables for this docType to be set up in the staging environment. We have generally been doing manual prod schema deploys once per day as well, so you should expect to see tables in prod in the next day or two as well.

Ping me if you're ready to start testing this and want to know more about monitoring data as it comes in.

**Pull request merged**
