### PR TITLE
Bug 1333405 - Create schema for the new 'modules' ping type

### PR DESCRIPTION
**Pull request by marco-c**
I've copied the common parts from another schema definition, I hope I haven't got anything wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/31)

### CODE REVIEW

**Comment by marco-c** [comment]
Some examples of a ping are in bug 1330833.

**Comment by marco-c** [comment]
I've added some tests in `validate_main.py` to validate sample pings.

In the ping generated on my Mac machine some required fields in the environment part (which is in common between different pings) are `null`. Any idea why? Should we remove those fields from the "required" list?

**Comment by marco-c** [comment]
Figured it out with @Dexterp37, I generated the Mac ping from a xpcshell test, so it has `null` fields where it shouldn't.
I'm going to generate a new one as soon as I have access to a Mac, but in the meantime I think this can be reviewed.

**Comment by Dexterp37** [comment]
The schema looks good to me. @mreid-moz , should you review this? And should we test this on Hindsight once pings start arriving?

**Comment by mreid-moz** [comment]
@Dexterp37 yes, this should definitely be tested on Hindsight before we merge/deploy. I took a quick look and it looks fine to me.

**Comment by Dexterp37** [comment]
@marco-c , can you check in with @trink to test this schema?

**Comment by marco-c** [comment]
I've tested the schema with @trink suggestions.
I've let hindsight run for a while and couldn't find any error (which is kind of suspicious):
```
194	main schema validation error: SchemaURI: #/properties/application/properties/buildId Keyword: pattern DocumentURI: #/application/buildId
1	saved-session schema validation error: SchemaURI: #/definitions/addon/properties/version Keyword: type DocumentURI: #/environment/addons/activeAddons/jetpack-extension%40dashlane.com/version
4	invalid submission: failed to parse offset:0 Invalid value.
33	saved-session schema validation error: SchemaURI: #/properties/clientId Keyword: type DocumentURI: #/clientId
4	crash schema validation error: SchemaURI: #/definitions/addon/properties/version Keyword: type DocumentURI: #/environment/addons/activeAddons/jetpack-extension%40dashlane.com/version
1	saved-session schema validation error: SchemaURI: #/properties/payload/properties/log Keyword: type DocumentURI: #/payload/log
9	invalid submission: failed to parse offset:0 The document is empty.
9	main schema validation error: SchemaURI: #/properties/clientId Keyword: type DocumentURI: #/clientId
1	main schema validation error: SchemaURI: #/definitions/addon/properties/updateDay Keyword: type DocumentURI: #/environment/addons/activeAddons/websecurity%40ati.org/updateDay
1	main schema validation error: SchemaURI: #/properties/creationDate Keyword: pattern DocumentURI: #/creationDate
6	main schema validation error: SchemaURI: #/properties/environment/properties/settings/properties/update/properties/autoDownload Keyword: type DocumentURI: #/environment/settings/update/autoDownload
78	main schema validation error: SchemaURI: #/definitions/addon/properties/version Keyword: type DocumentURI: #/environment/addons/activeAddons/jetpack-extension%40dashlane.com/version
14	saved-session schema validation error: SchemaURI: #/properties/environment/properties/build/properties/vendor Keyword: type DocumentURI: #/environment/build/vendor
1	main schema validation error: SchemaURI: #/properties/payload/properties/histograms Keyword: type DocumentURI: #/payload/histograms
4	main schema validation error: SchemaURI: #/definitions/addon/properties/name Keyword: type DocumentURI: #/environment/addons/activeAddons/floatnotes%40felix-kling.de/name
1	main schema validation error: SchemaURI: #/definitions/addon/properties/name Keyword: type DocumentURI: #/environment/addons/activeAddons/pano%40teramako.github.com/name
1	main schema validation error: SchemaURI: #/definitions/addon/properties/name Keyword: type DocumentURI: #/environment/addons/activeAddons/guiconfig%40slosd.net/name
3	main schema validation error: SchemaURI: #/properties/environment/properties/system/properties/os/properties/installYear Keyword: type DocumentURI: #/environment/system/os/installYear
4	main schema validation error: SchemaURI: #/definitions/addon/properties/signedState Keyword: type DocumentURI: #/environment/addons/activeAddons/aushelper%40mozilla.org/signedState
1	main schema validation error: SchemaURI: #/definitions/addon/properties/name Keyword: type DocumentURI: #/environment/addons/activeAddons/hqfpyxxhatwmljt%40cjetsryrunuc.net/name
1	saved-session schema validation error: SchemaURI: #/properties/payload/properties/threadHangStats Keyword: type DocumentURI: #/payload/threadHangStats
26	main schema validation error: SchemaURI: #/properties/environment/properties/settings/properties/update/properties/enabled Keyword: type DocumentURI: #/environment/settings/update/enabled
1	main schema validation error: SchemaURI: #/definitions/addon/properties/name Keyword: type DocumentURI: #/environment/addons/activeAddons/quicksearch%40peter.faj/name
1	crash schema validation error: SchemaURI: #/properties/environment/properties/settings/properties/update/properties/enabled Keyword: type DocumentURI: #/environment/settings/update/enabled
```

**Comment by Dexterp37** [comment]
Is the validation happening at all and are "modules" ping coming in? Definitely worthwhile double checking that.

**Comment by marco-c** [comment]
> Is the validation happening at all and are "modules" ping coming in? Definitely worthwhile double checking that.

I have no idea how to check if the validation is happening.

They are being received: https://gist.github.com/marco-c/d21a64daf639c029301642bde76156e9.

**Comment by Dexterp37** [comment]
> I have no idea how to check if the validation is happening.

That's something to check with @trink, just to exclude any problem with the schema validator plug-in.

**Comment by trink** [comment]
1) had to update the landfill request to pull in newer data
2) had to activate the modules schema in ping.lua

**Comment by marco-c** [comment]
After the updates, I still wasn't able to find any validation error. There was an error found if I purposedly introduced a bug in the schema, so it looks like the validation is actually happening now.

**Comment by Dexterp37** [comment]
Ok, fine with me then! @mreid-moz , do you want/need to take a closer look?

**Comment by mreid-moz** [comment]
Fine by me!

**Pull request merged**
