### PR TITLE
Shield Study doc_type JSON Schemas

### PR DESCRIPTION
**Pull request by gregglind**
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/19)

### CODE REVIEW

**Comment by mreid-moz** [comment]
I hate to advocate for __less__ documentation, but I don't think the `"title": "<field name> schema."` annotations are useful, and just clutter things up. Let's just use them when we have something to say.

---

Reviewed 3 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[shield-study/shield-study-addon.schema.json, line 4 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEUYigvVEYgRGFdGj:-KZhEUYigvVEYgRGFdGk:b-2s3xhi) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L4)):*
> ```JSON
>   "$schema": "http://json-schema.org/draft-04/schema#",
>   "type": "object",
>   "title": "Shield Common Format Payload Schema.",
> ```

C&P from the shield-study schema? This should be the study-addon-specific format, right?

---

*[shield-study/shield-study-addon.schema.json, line 5 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEY_b_SJvNOUOpVdh:-KZhEY_b_SJvNOUOpVdi:b-89a4l7) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L5)):*
> ```JSON
>   "type": "object",
>   "title": "Shield Common Format Payload Schema.",
>   "description": "Common fields for all Shield-Study doc_types.",
> ```

Ditto

---

*[shield-study/shield-study-addon.schema.json, line 38 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhImxdRgAWhFw69WSJ:-KZhImxezuP0xycysvqe:bkylkb0) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L38)):*
> ```JSON
>       "description": "Which version of the shield-studies-addon-utils."
>     },
>     "data": {
> ```

Should we make this data.details for consistency with the other two types?

---

*[shield-study/shield-study-addon.schema.json, line 55 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhDgps1FNea56QhR6k:-KZhDgps1FNea56QhR6l:bmxtw5p) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L55)):*
> ```JSON
>     "addon_version",
>     "shield_version",
>     "data"
> ```

Last we talked, `data` was not required.

---

*[shield-study/shield-study-error.schema.json, line 4 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhIOg47oRVBEQ5gSqB:-KZhIOg47oRVBEQ5gSqC:bjsg63d) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L4)):*
> ```JSON
>   "$schema": "http://json-schema.org/draft-04/schema#",
>   "type": "object",
>   "title": "Shield Common Format Payload Schema.",
> ```

Ditto - this should be the schema for error reporting only

---

*[shield-study/shield-study-error.schema.json, line 5 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhIV5LFN9gsvJcIm6e:-KZhIV5LFN9gsvJcIm6f:b-1osywe) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L5)):*
> ```JSON
>   "type": "object",
>   "title": "Shield Common Format Payload Schema.",
>   "description": "Common fields for all Shield-Study doc_types.",
> ```

And again

---

*[shield-study/shield-study-error.schema.json, line 74 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEoDmg3mMs1xXGx-f:-KZhEoDncGflXrVG7KTe:b-ipvwz2) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L74)):*
> ```JSON
>           "description": "Where did the error originate.",
>           "enum": [
>             null,
> ```

Do we need both `null` and `"unknown"`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-:-KZhIyVBJM_EF3u2PPMz:b-3s5fo3)*

**Comment by gregglind** [comment]
> I hate to advocate for less documentation, but I don't think the "title": "<field name> schema." annotations are useful, and just clutter things up. Let's just use them when we have something to say.

I like keeping the 'description' but will rip out title.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[shield-study/shield-study-addon.schema.json, line 4 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEUYigvVEYgRGFdGj:-KZhRAiWy5RCUw_wONRM:b-qssebl) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L4)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

C&P from the shield-study schema? This should be the study-addon-specific format, right?
</blockquote></details>

fixed.

---

*[shield-study/shield-study-addon.schema.json, line 5 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEY_b_SJvNOUOpVdh:-KZhRBkYhr_-iT_79qGU:b-7ql1td) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L5)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

fixed

---

*[shield-study/shield-study-addon.schema.json, line 38 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhImxdRgAWhFw69WSJ:-KZhRDEYf2bRJDiwSI3M:b-vspst2) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L38)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Should we make this data.details for consistency with the other two types?
</blockquote></details>

'data' is the top level field, which varies by doc_type.  

---

*[shield-study/shield-study-addon.schema.json, line 55 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhDgps1FNea56QhR6k:-KZhRKaYUobQvE_xS_0l:b9oo0z8) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L55)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Last we talked, `data` was not required.
</blockquote></details>

data is the top level field, I claim it's required.

---

*[shield-study/shield-study-error.schema.json, line 4 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhIOg47oRVBEQ5gSqB:-KZhRPGOBs2MjWEbtYtO:b-7ql1td) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L4)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Ditto - this should be the schema for error reporting only
</blockquote></details>

fixed

---

*[shield-study/shield-study-error.schema.json, line 5 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhIV5LFN9gsvJcIm6e:-KZhRQOznENcstqF_YPY:b-7ql1td) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L5)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

And again
</blockquote></details>

fixed

---

*[shield-study/shield-study-error.schema.json, line 74 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEoDmg3mMs1xXGx-f:-KZhRUIUHabtTmAMrudl:baxzghg) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L74)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Do we need both `null` and `"unknown"`?
</blockquote></details>

I am tempted to make it NOT NULLABLE.  Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-:-KZhQws9A534jdDcWG-x:bzas06n)*

**Comment by mreid-moz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[shield-study/shield-study-addon.schema.json, line 38 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhImxdRgAWhFw69WSJ:-KZhV5L0kyEI2hEozjWs:b-aoh378) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-addon.schema.json#L38)):*
<details><summary><i>Previously, gregglind (Gregg Lind) wrote…</i></summary><blockquote>

'data' is the top level field, which varies by doc_type.  
</blockquote></details>

you'd have to add a field within "data" called "details" (or "attributes" per IRC).

---

*[shield-study/shield-study-error.schema.json, line 74 at r1](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-KZhEoDmg3mMs1xXGx-f:-KZhVNb7ZDhLdDfqBWog:b-38xjup) ([raw file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/4fe6ef4dc19d4f7e3c6cb7d13a5c599bcb245ae2/shield-study/shield-study-error.schema.json#L74)):*
<details><summary><i>Previously, gregglind (Gregg Lind) wrote…</i></summary><blockquote>

I am tempted to make it NOT NULLABLE.  Thoughts?
</blockquote></details>

I would be inclined to allow `null` and scrap "unknown"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19)*

**Comment by mreid-moz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/mozilla-pipeline-schemas/19#-:-K_4acs_VeqzUNlCnxDT:bnfp4nl)*

**Comment by gregglind** [comment]
16:06 <@mreid> gregglind: the existing test coverage is limited to https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/validation/telemetry/validate_main.py

**Pull request merged**
