### PR TITLE
Add page for china build to activity stream impression_stats

### PR DESCRIPTION
**Pull request by ncloudioj**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant
- [ ] Scan the PR and verify that no changes (particularly to `.circleci/config.yml`) will cause environment variables (particularly credentials) to be exposed in test logs
- [ ] Trigger the `integration` CI test by pushing this revision [as discussed in the README](https://github.com/mozilla-services/mozilla-pipeline-schemas#packaging-and-integration-tests-optional)

For glean changes:
- [ ] Update `include/glean/CHANGELOG.md`

@jklukas r?

### CODE REVIEW

**Comment by jklukas** [comment]
Running integration tests and then  I'll merge.

**Comment by l-hedgehog** [comment]
Thank you!

I couldn't help but notice this PR is for activity-stream/impression-stats only. How do you feel about also whitelisting this in activity-stream/events ?

**Comment by ncloudioj** [comment]
> How do you feel about also whitelisting this in activity-stream/events?

The `activity-stream/events` was recently added in Firefox 72. If the custom build is a fork off Activity Stream 68, event pings won't be sent to here at all. We can whitelist it once it reaches to 72 or beyond.

**Comment by l-hedgehog** [comment]
> The `activity-stream/events` was recently added in Firefox 72. If the custom build is a fork off Activity Stream 68, event pings won't be sent to here at all. We can whitelist it once it reaches to 72 or beyond.

Within the browser console, I can see `TelemetryFeed.sendStructuredIngestionEvent` called &  `POST` requests sent to `https://incoming.telemetry.mozilla.org/submit/activity-stream/events/1/{uuid}` in Fx 72 when clicking around the page.

**Comment by ncloudioj** [comment]
Correct, that's because this ping was migrated from Tiles to here in 72.

To be clear, only `activity-stream/impression_stats` was migrated back in 68, `events` in 68 still ping the Tiles' endpoint, which will be decommissioned soon.

**Comment by l-hedgehog** [comment]
Thank you, I can see the data in `activity-stream/impression-stats` now.

> 
> Correct, that's because this ping was migrated from Tiles to here in 72.
> 

I can see the calls & pings when clicking around in our forked page.

The web side of our implementation is indeed Fx 68 based, but it's connected to `TelemetryFeed` and other browser side components that shipped with whichever version of Fx being used, not some forked copy in our extension.

**Comment by ncloudioj** [comment]
OK, I will add it to `activity-stream/events`.

**Pull request merged**
