### PR TITLE
Bug 1400939 Add parquet output for URI errors

### PR DESCRIPTION
**Pull request by trink**
r? @mreid-moz

### CODE REVIEW

**Comment by mreid-moz** [comment]
Can you split the pioneer-study stuff into a separate commit or PR?

**Comment by trink** [comment]
I could but is there a point?  It is just the generated artifacts that someone forgot to check-in but are already part of the currently deployed package.

**Comment by mreid-moz** [comment]
Not really, just that they don't have anything to do with the commit message here.

**Comment by trink** [comment]
done

**Pull request merged**
