### PR TITLE
Bug 1783722 - Add notification_not_shown_reason to wdba schema

### PR DESCRIPTION
**Pull request by bytesized**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by fbertsch — APPROVED** [review]

**Comment by bytesized** [comment]
Did I cause this CI test failure? It doesn't look related to my code, to me.

**Comment by fbertsch** [comment]
> Did I cause this CI test failure? It doesn't look related to my code, to me.

Agreed, it's an issue with a dependency. Hold tight.

**Comment by fbertsch** [comment]
@bytesized can you rebase?

**Comment by bytesized** [comment]
Uh oh. I rebased on master instead of main and that does _not_ seem to be what I wanted and now I'm not sure how to fix it because the rebase does not apply cleanly.

**Comment by bytesized** [comment]
The only thing I know how to do from here is to close this and start all over again, so I guess I'll do that :(

**Comment by bytesized** [comment]
Moved to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/744

**Pull request closed without merging**
